### ISSUE TITLE
Doesnt work with latest create version

### ISSUE THREAD

**Issue by Plasman888** [cvrunmin/CreateSpawnerBoxer#1]

**Comment by cvrunmin** [comment]
hi! can you provide more information? For example:
- the crash report
- what minecraft version you are running, and what loader you are using
- what Create version you have
- what CreateSpawnerBoxer version you have
- any other mods you have installed

**Comment by Plasman888** [comment]
Sure man I'll let you know when I reach home

**Comment by Plasman888** [comment]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create: SpawnerBoxer' (createspawnerboxer) 0.1.0+fabric-1.20.1-6 with any version that is compatible with:
		 - create 0.5.1-f-build.1417+mc1.20.1
More details:
	 - Mod 'Create: SpawnerBoxer' (createspawnerboxer) 0.1.0+fabric-1.20.1-6 requires version 0.5.1-f-build.1335+mc1.20.1 of mod 'Create' (create), but only the wrong version is present: 0.5.1-f-build.1417+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Plasman888** [comment]
I have alotta other mods but idt they are they issue, if u wan me send my mod list lmk

**Comment by Plasman888** [comment]
im using fabric btw 1.20.1 0.15.10 btw, with spawnerbox 0.1.0 for fabric

**Comment by cvrunmin** [comment]
have uploaded a new build for the fix on modrinth. check if this fix the issue

**Comment by Plasman888** [comment]
sure let me try

**Comment by Plasman888** [comment]
nice it works
